# Generated by Django 2.1.1 on 2018-10-26 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='answerfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ans',
            },
        ),
        migrations.CreateModel(
            name='loginfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='questionfiles',
            fields=[
                ('idform', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'qns',
            },
        ),
        migrations.AddField(
            model_name='answerfiles',
            name='idform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formapp.questionfiles'),
        ),
    ]
